# Generated by Django 5.1.7 on 2025-04-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_item_image_url_item_image_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='image_url',
        ),
    ]
